server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql-auth:3306/authdb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


chitchat:
  jwt:
    base64-secret: cHJldmlvdXNjb25zdGFudGx5ZGl2aWRlYmFzZXBsYWludHJhdmVsZGlzaHdyYXBwZWQ=
    access-token-validity-in-seconds: 86400
    refresh-token-validity-in-seconds: 86400
