server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
        
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

management:
  endpoints:
    web:
      exposure:
        include: refresh, routes
