server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://mysql-notification:3306/notificationdb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

